Added hoist/scopeand if declarations
redacademy/js-fundamentals pull request #3
Opened 2017-02-06 23:07 UTC by edwardlanto

!!!!! STOP AND READ !!!!!

If the dropdown above says "base fork: lord/master", you are submitting your change to ALL USERS OF SLATE, not just your company. This is probably not what you want. Click "base fork" to change it to the right place.

If you're actually trying to submit a change to upstream Slate, please submit to our dev branch, PRs sent to the master branch are generally rejected.

2017-02-06 23:30 UTC, BlakeTurner requested changes
Remember that you're writing this code for your classmates. Try to be as clear and simple as possible.

2017-02-06 23:30 UTC, BlakeTurner commented on source/includes/_hoist.md
> +//Before Hoist
I'd put the comment before the code for both of these: 
```js
// Before Hoise
var name = "Warren";
```

2017-02-06 23:30 UTC, BlakeTurner commented on source/includes/_hoist.md
> +* Whether before or after hoist, the 'if' statement remains
Could you provide an example of this?

2017-02-06 23:30 UTC, BlakeTurner commented on source/includes/_hoist.md
> +iDeclareBankruptcy = function(){} // Function expression
I think this section would be ore useful if the 'before' and 'after' were more obvious. I found it confusing.

2017-02-06 23:30 UTC, BlakeTurner commented on source/includes/_hoist.md
> +var iDeclareBankruptcy(){} //Hoisted variable declaration
This is an invalid JS statement. (try it in your console)

2017-02-06 23:30 UTC, BlakeTurner commented on source/includes/_hoist.md
> +* However the assignment part of the variable remains unmoved.
Assignment is not 'part' of a variable. 

If we have:
```js
var foo = 'bar';
```

We have the variable declaration:

```js
var foo;
```

And the assignment operation:

```js
foo = 'bar';
```

2017-02-06 23:30 UTC, BlakeTurner commented on source/includes/_hoist.md
> +* Functions are hoisted first, before variables.
Could you provide an example of broken JS if we use a assign a function to a variable instead of using a function declaration?

2017-02-06 23:41 UTC, edwardlanto commented on source/includes/_hoist.md
> +//Before Hoist
k.

2017-02-06 23:41 UTC, edwardlanto commented on source/includes/_hoist.md
> +//Before Hoist
jk LOL

2017-02-07 00:19 UTC, BlakeTurner approved these changes

2017-02-07 00:19 UTC, merged